version: '3.4'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka/
    depends_on:
      - eureka-server
  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "9091:9091"
    restart: on-failure
  microservice-candidat:
    build:
      context: ./microservice-candidat
    ports:
      - "9082:9082"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka/
    depends_on:
      - eureka-server
  microservice-auth:
    build:
      context: ./microservice-auth
    ports:
      - 9086:9086
    container_name: microservice-auth
    image: node-app-image
    restart: on-failure
    environment:
      - MONGO_URI=mongodb+srv://mariembok:mariembok1998@cluster0.ucbvufk.mongodb.net/
      - EUREKA_DEFAULTZONE=eureka-server
      - EUREKA_PORT=9091
      - HOSTNAME=microservice-auth
      - PORT=9086
    depends_on:
      - mongodb
      - eureka-server
  db-mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: microser
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "3306:3306"     
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: on-failure
  
