logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: microservice-candidat
          uri: lb://microservice-candidat
          predicates:
            - Path=/api/candidat/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: microservice-review
          uri: lb://microservice-review
          predicates:
            - Path=/api/review/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: microservice-auth
          uri: lb://microservice-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/