debug: false
server:
  port: 9084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
spring:
  application:
    name: microservice-review
  console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:mysql://10.0.2.15:3306/microser?serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update